<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Operations;


/**
 * PostSitesSiteRefSections201ApplicationJSON - Created
 * 
 * @package basekit\SiteBuilder\Models\Operations
 * @access public
 */
class PostSitesSiteRefSections201ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('section')]
    #[\JMS\Serializer\Annotation\Type('basekit\SiteBuilder\Models\Shared\Section')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\basekit\SiteBuilder\Models\Shared\Section $section = null;
    
	public function __construct()
	{
		$this->section = null;
	}
}
