<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Operations;


class PostSitesSiteRefSectionsRequestBody
{
    /**
     * Only used when sibling is present, valid values are above or below
     * 
     * @var ?\basekit\SiteBuilder\Models\Operations\PostSitesSiteRefSectionsRequestBodyPosition $position
     */
	#[\JMS\Serializer\Annotation\SerializedName('position')]
    #[\JMS\Serializer\Annotation\Type('enum<basekit\SiteBuilder\Models\Operations\PostSitesSiteRefSectionsRequestBodyPosition>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostSitesSiteRefSectionsRequestBodyPosition $position = null;
    
    /**
     * sectionRef of another section to be used with the position field. If blan kthe section will be added to  bottom of the main zone
     * 
     * @var ?string $siblingRef
     */
	#[\JMS\Serializer\Annotation\SerializedName('siblingRef')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $siblingRef = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('template')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $template;
    
	public function __construct()
	{
		$this->position = null;
		$this->siblingRef = null;
		$this->template = "";
	}
}
