<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Operations;


class PostSitesSiteRefSectionsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\basekit\SiteBuilder\Models\Operations\PostSitesSiteRefSections201ApplicationJSON $postSitesSiteRefSections201ApplicationJSONObject
     */
	
    public ?PostSitesSiteRefSections201ApplicationJSON $postSitesSiteRefSections201ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postSitesSiteRefSections201ApplicationJSONObject = null;
	}
}
