<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Operations;


class PutSitesSiteRefPagesPageRefSectionsSectionRefWidgetsWidgetRefResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\basekit\SiteBuilder\Models\Shared\Widget $widget
     */
	
    public ?\basekit\SiteBuilder\Models\Shared\Widget $widget = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->widget = null;
	}
}
