<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Shared;


class Section
{
	#[\JMS\Serializer\Annotation\SerializedName('ref')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ref;
    
	#[\JMS\Serializer\Annotation\SerializedName('template')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $template;
    
    /**
     * $widgets
     * 
     * @var array<\basekit\SiteBuilder\Models\Shared\Widget> $widgets
     */
	#[\JMS\Serializer\Annotation\SerializedName('widgets')]
    #[\JMS\Serializer\Annotation\Type('array<basekit\SiteBuilder\Models\Shared\Widget>')]
    public array $widgets;
    
	public function __construct()
	{
		$this->ref = "";
		$this->template = "";
		$this->widgets = [];
	}
}
