<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace basekit\SiteBuilder\Models\Shared;


/**
 * Widget - OK
 * 
 * @package basekit\SiteBuilder\Models\Shared
 * @access public
 */
class Widget
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('basekit\SiteBuilder\Models\Shared\WidgetData')]
    public WidgetData $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('ref')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $ref;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	public function __construct()
	{
		$this->data = new \basekit\SiteBuilder\Models\Shared\WidgetData();
		$this->ref = 0;
		$this->type = "";
	}
}
